server:
  port: 8080
  error:
    path: /error
  servlet:
    context-path: /api/v1
#============
# 日志级别
#============
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    druid.sql.Statement: debug
    druid.sql.ResultSet: debug
spring:
  profiles:
    active: default,shiro
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ## 项目启动的时候自动更新表结构
      ddl-auto: update
    ## 指定建表引擎使用innodb
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    druid:
      filters: stat,wall,slf4j
      filter:
        commons-log:
          statement-log-enabled: true
          statement-executable-sql-log-enable: true
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


# ==============
# mybatis 配置
# ==============
mybatis:
  mapper-locations: mapper/*Mapper.xml

#===============
# pageHelper 配置
#===============
pagehelper:
  helper-dialect: mysql
  params: count=countSql
